### ISSUE TITLE
Usage on N5550 with kernel 5.4

### ISSUE THREAD

**Issue by hapklaar** [jncronin/ich7_gpio#1]
Just installed Open Media Vault on my N5550 and found the system leds and HDD leds are not working. Found this repo by chance that addresses similar issues.

I'm aware you've been working on this over 8 years ago, so you might have forgotten all about it. Was just wondering if you have a newer version that could be compiled for a more recent kernel, as the usage of create_proc_entry has been removed in kernel 3.10. Not sure if this would even get the HDD leds working again though, but had to ask.

The error I'm getting during compilation is: 

```
root@N5550-OMV:~/download/ich7/ich7_gpio# make modules
make -C /lib/modules/5.4.0-0.bpo.4-amd64/build M=/root/download/ich7/ich7_gpio modules
make[1]: Entering directory '/usr/src/linux-headers-5.4.0-0.bpo.4-amd64'
  CC [M]  /root/download/ich7/ich7_gpio/ich7_gpio.o
/root/download/ich7/ich7_gpio/ich7_gpio.c: In function ‘nas_gpio_init’:
/root/download/ich7/ich7_gpio/ich7_gpio.c:771:14: error: implicit declaration of function ‘create_proc_entry’; did you mean ‘remove_proc_entry’? [-Werror=implicit-function-declaration]
  ich7_proc = create_proc_entry(PROCFS_NAME, 0, NULL);
              ^~~~~~~~~~~~~~~~~
              remove_proc_entry
/root/download/ich7/ich7_gpio/ich7_gpio.c:771:12: warning: assignment to ‘struct proc_dir_entry *’ from ‘int’ makes pointer from integer without a cast [-Wint-conversion]
  ich7_proc = create_proc_entry(PROCFS_NAME, 0, NULL);
            ^
/root/download/ich7/ich7_gpio/ich7_gpio.c:780:11: error: dereferencing pointer to incomplete type ‘struct proc_dir_entry’
  ich7_proc->proc_fops = &proc_ich7_operations;
           ^~
cc1: some warnings being treated as errors
make[3]: *** [/usr/src/linux-headers-5.4.0-0.bpo.4-common/scripts/Makefile.build:271: /root/download/ich7/ich7_gpio/ich7_gpio.o] Error 1
make[2]: *** [/usr/src/linux-headers-5.4.0-0.bpo.4-common/Makefile:1665: /root/download/ich7/ich7_gpio] Error 2
make[1]: *** [/usr/src/linux-headers-5.4.0-0.bpo.4-common/Makefile:179: sub-make] Error 2
make[1]: Leaving directory '/usr/src/linux-headers-5.4.0-0.bpo.4-amd64'
make: *** [Makefile:7: modules] Error 2
```

thank you for your time!

**Comment by jncronin** [comment]
The module will need significant fixing to get it working with a modern kernel - unfortunately the linux kernel API has changed significantly in the last 8 years.  I do not, I'm afraid, have a N5500 to work on now, so it is unlikely I'll be able to make the appropriate changes.

Modern kernels do have built-in support for the ICH7 GPIOs though - you may want to look at the gpio_ich module or even using one of the led modules directly - for example the leds-ss4200 module appears to use an ICH7 and would only need the GPIO pins changing.  For the N5500 these are:

Pin 3 - Orange system LED
Pin 24 - Blue USB Copy LED
Pin 25 - Red Fail LED
Pin 27 - Green SATA1 LED
Pin 28 - Blue Power LED

All other LEDs (e.g. for other drives) are controlled by the relevant SATA controller and driver, so if these aren't working it suggests an issue with those that cannot be fixed by fiddling with the LEDs attached to the GPIO ports on the ICH7.

**Comment by hapklaar** [comment]
The HDD leds are mounted on a N5200 HDD backplane, which is connected to the main board. I guess something Thecus specific is going on here.

Thanks for responding!
